apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  selector:
    app: school-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 80  
