apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: school-app
  replicas: 2
  template:
    metadata:
      labels:
        app: school-app
    spec:
      containers:
      - name: school-app
        image: clibercastillo/school-app:1.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
