name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AWS_PROFILE_NAME: default
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  REGISTRY: ${{ secrets.ECR_REGISTRY }}
  REPOSITORY: school
  IMAGE_TAG: ${{ github.run_number }}
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: $AWS_ACCESS_KEY_ID
        aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Deployment
        uses: Pablommr/kubernetes-eks@v1.2.0
        env:
          KUBE_YAML: kubernetes/school-app.yml

      - name: Service
        uses: Pablommr/kubernetes-eks@v1.2.0
        env:
          KUBE_YAML: kubernetes/school-app-service.yml